{{- if .Values.jibri.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jibri.fullname" . }}
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
data:
  XMPP_SERVER: '{{ include "jitsi-meet.xmpp.server" . }}'
  JIBRI_BREWERY_MUC: '{{ .Values.jibri.breweryMuc }}'
  JIBRI_RECORDING_DIR: '{{ .Values.jibri.recordingDir | default "/data/recordings" }}'
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: "{{ if and .Values.jibri.vimeo.enable .Values.jibri.recording }}/config/sync.py{{ else }}/config/finalize.sh{{ end }}"
  {{- if and .Values.jibri.vimeo.enable .Values.jibri.recording }}
  # Variaveis para o Vimeo
  VIMEO_SYNC: "/config/sync.py"
  VIMEO_PENDING: "/config/pending.py"
  VIMEO_RETRY: "/config/retry.py"
  {{- end }}  
  
  JIBRI_STRIP_DOMAIN_JID: muc
  DISPLAY: ":0"
  JIBRI_SINGLE_USE_MODE: {{ .Values.jibri.singleUseMode | default false | quote }}
  {{- range $key, $value := .Values.jibri.extraEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
{{- end }}
